### ISSUE TITLE
Can no longer use response()->json() in error handling

### ISSUE THREAD

**Issue by RobinJ1995** [generationtux/jwt-artisan#11]
`Laravel Framework version Lumen (5.2.6) (Laravel Components 5.2.*)`

As per Lumen's documentation, I have defined my own error handling behaviour in `app/Exceptions/Handler.php`;

``` php
public function render($request, Exception $e)
{
    if ($e instanceof ValidationException)
        return parent::render ($request, $e);

    $obj = [
        'error' => true,
        'message' => $e->getMessage ()
    ];

    if (env ('APP_DEBUG', false))
    {
        $obj['file'] = $e->getFile ();
        $obj['line'] = $e->getLine ();
        $obj['trace'] = $e->getTrace ();
    }

    return response ()->json ($obj);
}
```

As you can see, I use `response ()->json ()` to return a response in JSON format. However, any time an error occurs, the JWT library interferes and causes another exception to be thrown, causing that one to be reported back to the client instead of the original exception.
![screenshot from 2016-05-06 13-43-59](https://cloud.githubusercontent.com/assets/3089559/15073278/9ee3679e-1390-11e6-98be-b55aea01b8e3.png)

**Comment by kyleferguson** [comment]
So, as I'm sure you've gathered, the reason this exception is being thrown is because no token was provided on the request. The way we have implemented this in our work is the JWT middleware is only applied on routes that we always expect tokens to be present. So if no token is present, this exception would be what we expect to see come through, since if the user is not authenticated then they shouldn't be able to reach any other code that would potentially thrown an exception.

So from a high level view we have

```
route1 (with JWT, requires authentiation)
    - whatever code behind the route that may potentially throw exception

route2 (without JWT, doesn't require authentication)
    - whatever code behind the route that may potentially throw exception
```

If we hit route 1 without a token, then we would expect to see the JWT exception, as user authentication is required to hit this route so no code below it would be executed.

If we hit route 2 without a token, JWT check is never hit because authentication is not required so the code executes and throws whatever exception it may or may not throw.

Let me know if that helps.

**Comment by molteber** [comment]
I have the excact same problem. Using it with Lumen.
I have `/login` which does not require any tokens or whatevery. When i throw a exception it throws the same exception as the image provded over here.
`/login` does not have any middlewares assigned to it, nor do i have any global middlewares assigned by myself, not sure if lumen adds a couple for the application.

Using this snippet before i throw the exception make it not trigger the no token set exception:
`$jwt->setToken("fake-token");`
