### ISSUE TITLE
Wrong number of segments error

### ISSUE THREAD

**Issue by adamkelso** [generationtux/jwt-artisan#14]
Hey guys,

First off, thanks for making this package. It's been a nice addition to my stack. That being said, I do occasionally get an error with the following stack trace.

lumen.ERROR: UnexpectedValueException: Wrong number of segments in /var/www/html/shipping/vendor/firebase/php-jwt/src/JWT.php:67
Stack trace:
#0 /var/www/html/shipping/vendor/generationtux/jwt-artisan/src/Drivers/FirebaseDriver.php(64): Firebase\JWT\JWT::decode('Error', 'sp85twcodSCl8CR...', Array)
#1 /var/www/html/shipping/vendor/generationtux/jwt-artisan/src/JwtToken.php(180): GenTux\Jwt\Drivers\FirebaseDriver->decodeToken('Error', 'sp85twcodSCl8CR...', 'HS256')
#2 /var/www/html/shipping/vendor/generationtux/jwt-artisan/src/GetsJwtToken.php(72): GenTux\Jwt\JwtToken->payload(NULL)
#3 /var/www/html/shipping/app/Http/Controllers/Controller.php(19): App\Http\Controllers\Controller->jwtPayload()

In my base controller class's constructor I'm simply calling

`$payload = $this->jwtPayload()`

when the error occurs.

**Comment by kyleferguson** [comment]
I haven't tested this, but I'm assuming this happens when either a token doesn't exist in the header, or it is not a well formed token (IE missing signature at the end or something). I'll test it out tomorrow and see if it's something else I'm missing.

Probably need to handle those cases a little cleaner if thats the case. Theres a new release in progress that will have a slightly different API, but a more complete feature set. I'm going to leave this open so I can make sure those cases are handled at least in the next version.

**Comment by adamkelso** [comment]
Cool. Thanks.

**Comment by tonipepperoni** [comment]
@kyleferguson yes in my login app I always get this error and my authorization header looks like this
