### ISSUE TITLE
Non-expiring token

### ISSUE THREAD

**Issue by mantchido** [generationtux/jwt-artisan#3]
I would like my generated tokens to be a non-expiry token. How can I do that? When I tried generating one without specifying an payload expiry time, subsequent ones where all the same. So all my clients will have same token if I choose to implement it this way. How can I properly generate token that will not expire?

**Comment by kyleferguson** [comment]
Really, all tokens should expire after some time. If you would like to implement a feature like remember me so that the user does not need to re authenticate, I would follow this type of flow:
- User authenticates to receive a token and wants to be remembered
- Set a `remember_me=true` flag in the payload, and set the expire time for the token to be 30 days (or whatever time frame`
- Every time the token is authenticated within that 30 days and remember_me is true, create a new token for another 30 days and return it to be used and replace the old one with the new one

This will allow the user to essentially be remembered forever, provided they use the app within 30 days of receiving the latest token. If they don't use the app within that timeframe, then the token will be invalid and they will need to re-authenticate. (Obviously, you can set whatever timeframe you think is appropriate)
